spring:
    application:
        name: broker-system

    artemis:
        mode: native
        broker-url: tcp://localhost:61616
        user: admin
        password: admin

    jackson:
        serialization:
            write-dates-as-timestamps: false

server:
    port: 8082

camel:
    route:
        sol1:
            enabled: false

logging:
    level:
        com.instantpayments.bs: DEBUG
        org.apache.camel: INFO

---
spring:
    config:
        activate:
            on-profile: sol1

camel:
    route:
        sol1:
            enabled: true

---
spring:
    config:
        activate:
            on-profile: sol2

camel:
    route:
        sol1:
            enabled: false
