# Debezium Server Configuration
# Source: PostgreSQL CDC  ->  Sink: HTTP (Audit Service)

# ===== Sink (output) =====
debezium.sink.type=http
debezium.sink.http.url=http://audit-service:8084/api/v1/cdc/payments
debezium.sink.http.content-type=application/json

# ===== Source (input) =====
debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.offset.storage.file.filename=/debezium/data/offsets.dat
debezium.source.offset.flush.interval.ms=0

debezium.source.database.hostname=postgres
debezium.source.database.port=5432
debezium.source.database.user=debezium
debezium.source.database.password=dbz_pass
debezium.source.database.dbname=instantpayments

debezium.source.topic.prefix=poc
debezium.source.table.include.list=public.payments
debezium.source.plugin.name=pgoutput
debezium.source.publication.autocreate.mode=disabled
debezium.source.publication.name=dbz_publication
debezium.source.slot.name=debezium_slot

# Schema history
debezium.source.schema.history.internal=io.debezium.storage.file.history.FileSchemaHistory
debezium.source.schema.history.internal.file.filename=/debezium/data/schema-history.dat

# Format: output whole event envelope as JSON
debezium.format.value=json
debezium.format.value.schemas.enable=false
